TARGET_EXE=sample
CPP_SOURCES=main.cpp
TARGET_TYPE=exe

include ../build/tools_env.mk
include ../build/wxwidgets_env.mk

CFLAGS+=$(WX_CFLAGS)
LDFLAGS+=$(WX_LDFLAGS)

INCLUDES=../libwxmagic

include ../build/buildsys.mk

