LIBNAME=libwxMagic
CPP_SOURCES=wxMagic.cpp
TARGET_TYPE=statlib

include ../build/tools_env.mk
include ../build/wxwidgets_env.mk

CFLAGS+=$(WX_CFLAGS)

include ../build/buildsys.mk


# DO NOT DELETE

$(OBJ_DIR)/wxMagic.o: wxMagic.h
